meta_product_name: "CICLO"
meta_title: "CICLO - Get the best route with real time reports from other cyclists"
meta_description: "The first web-app to find real time information about bike touring routes & see other touring cyclists around you. In one click you can easly reports new info on the map or contact with bikepackers."
meta_image: "og_image.png" # should exist in `app/assets/images/`
twitter_account: ""   # required for Twitter Cards
